#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

if {[llength $argv] != 3} {
    puts "Usage:   ./auto_pipeline_add_table <pipeline_name> <schema_name> <table_name>"
    exit 1
}
set pipeline_name [lindex $argv 0]
set schema_name   [lindex $argv 1]
set table_name    [lindex $argv 2]

set tmpfile1 "/tmp/auto_pipeline_at1_[pid]"
set tmpfile2 "/tmp/auto_pipeline_at2_[pid]"
set tmpfile3 "/tmp/auto_pipeline_at3_[pid]"

cd /dbagiga/gs-odsx
log_file -noappend $tmpfile1
spawn ./odsx.py dataengine oracle-cdc pipeline schema-structure-management add-table

expect "Select pipeline number to add table"
log_file

set fh [open $tmpfile1 r]
set content1 [read $fh]
close $fh
file delete $tmpfile1

regsub -all {\x1b\[[0-9;]*m} $content1 "" clean1
set row_num ""
foreach line [split $clean1 "\n"] {
    if {[regexp "\\|\\s+(\\d+)\\s+\\|\\s*${pipeline_name}\\s*\\|" $line -> num]} {
        set row_num $num
        break
    }
}

if {$row_num eq ""} {
    puts "\nPipeline '$pipeline_name' not found."
    exit 1
}

sleep 1
send -- "$row_num"
sleep 1
send -- "\n"

log_file -noappend $tmpfile2
expect "Select schema number"
log_file

set fh [open $tmpfile2 r]
set content2 [read $fh]
close $fh
file delete $tmpfile2

regsub -all {\x1b\[[0-9;]*m} $content2 "" clean2
set schema_num ""
foreach line [split $clean2 "\n"] {
    if {[regexp "\\|\\s+(\\d+)\\s+\\|\\s*${schema_name}\\s*\\|" $line -> num]} {
        set schema_num $num
        break
    }
}

if {$schema_num eq ""} {
    puts "\nSchema '$schema_name' not found."
    exit 1
}

sleep 1
send -- "$schema_num"
sleep 1
send -- "\n"

log_file -noappend $tmpfile3
expect "Select table number"
log_file

set fh [open $tmpfile3 r]
set content3 [read $fh]
close $fh
file delete $tmpfile3

regsub -all {\x1b\[[0-9;]*m} $content3 "" clean3
set tbl_num ""
foreach line [split $clean3 "\n"] {
    if {[regexp "\\|\\s+(\\d+)\\s+\\|\\s*\\S+\\s*\\|\\s*${table_name}\\s*\\|" $line -> num]} {
        set tbl_num $num
        break
    }
}

if {$tbl_num eq ""} {
    puts "\nTable '$table_name' not found in schema '$schema_name'."
    exit 1
}

sleep 1
send -- "$tbl_num"
sleep 1
send -- "\n"

expect "Continue? (yes/no):"
sleep 1
send -- "y"
sleep 1
send -- "\n"

expect "Do you want to remove columns"
sleep 1
send -- "N"
sleep 1
send -- "\n"

expect eof
