#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /giga/gs-odsx
spawn ./odsx.py servers service start
# All servers
expect "for exit"
sleep 0.2
send -- "\r"
# Verify
expect "Are you sure want to start all servers"
sleep 0.2
send -- "y"
sleep 0.2
send -- "\r"

expect eof
