#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

if {[llength $argv] != 1} {
    puts "Usage:   ./auto_export_pipeline <pipeline_name|all>"
    exit 1
}
set pipeline_name [lindex $argv 0]
set tmpfile "/tmp/auto_pipeline_[pid]"

cd /dbagiga/gs-odsx
log_file -noappend $tmpfile
spawn ./odsx.py dataengine oracle-cdc pipeline pipeline-operations export-pipeline

expect "or all): "
log_file

if {$pipeline_name eq "all"} {
    sleep 1
    send -- "a"
    sleep 0.3
    send -- "l"
    sleep 0.3
    send -- "l"
    sleep 1
    send -- "\n"
    expect eof
    exit 0
}

set fh [open $tmpfile r]
set content [read $fh]
close $fh
file delete $tmpfile

regsub -all {\x1b\[[0-9;]*[a-zA-Z]} $content "" clean
regsub -all {\r} $clean "" clean
set row_num ""
foreach line [split $clean "\n"] {
    if {[regexp "\\|\\s+(\\d+)\\s+\\|\\s*${pipeline_name}\\s*\\|" $line -> num]} {
        set row_num $num
        break
    }
}

if {$row_num eq ""} {
    puts "\nPipeline '$pipeline_name' not found."
    exit 1
}

sleep 1
send -- "$row_num"
sleep 1
send -- "\n"

expect eof
