#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py dataengine oracle-cdc pipeline pipeline-operations create-pipeline

expect {
    "Enter new pipeline name" {
        interact
    }
    eof {
    }
}
