#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

if {[llength $argv] != 1} {
    puts "Usage:   ./auto_import_datasource <Datasource_name>"
    exit 1
}

set arg [lindex $argv 0]
if {[string match "*.json" $arg]} {
    set filename $arg
} else {
    set filename "${arg}.json"
}

set tmpfile "/tmp/auto_datasource_[pid]"

cd /dbagiga/gs-odsx
log_file -noappend $tmpfile
spawn ./odsx.py dataengine oracle-cdc datasource import-datasource

expect "Select file number"
log_file

set fh [open $tmpfile r]
set content [read $fh]
close $fh
file delete $tmpfile

regsub -all {\x1b\[[0-9;]*m} $content "" clean

# Escape dots in filename so they match literally in the regex
regsub -all {[.]} $filename {[.]} escaped_filename

set row_num ""
foreach line [split $clean "\n"] {
    if {[regexp "\\|\\s+(\\d+)\\s+\\|\\s*${escaped_filename}\\s*\\|" $line -> num]} {
        set row_num $num
        break
    }
}

if {$row_num eq ""} {
    puts "\nFile '$filename' not found in Tabler."
    exit 1
}

sleep 1
send -- "$row_num"
sleep 1
send -- "\n"

expect eof
