current:
  db2:
    config: null
    jars:
      db2ccLicense: db2jcc_license_cu-4.16.53.jar
      db2ccjar: db2jcc-4.26.14.jar
      db2feederJar: db2feeder-1.0.0.jar
    scripts: null
  data-integration:
    dim:
    mdm:
    flink:
  data-validator:
    jars:
      serverjar: data-validator-server-0.0.1-SNAPSHOT.jar
      agentjar: data-validator-agent-0.0.1-SNAPSHOT.jar
  grafana:
    catalog:
      jars:
        catalogjar: catalogue-service.jar
    dashboards:
    gsconfig: gs_config.yaml
  gs:
    config:
      log:
        xap_logging: xap_logging.properties
      services: gsa.service
      license:
        gslicense: gs-license.txt
      metrics:
        metricsxml: metrics.xml.template
      space:
        spacepropertyfile: space.properties
      ts:
        criteria: TSDirtyBit
        spaceproperty: spaceproperty.properties
    jars:
      ts:
        tieredStorageBuild: tiered_storage_jar-0.1.jar
      space:
        spacejar: in_memory_jar-0.1.jar
      zookeeper:
        zkjars:
          - curator-client-5.2.1.jar
          - curator-framework-5.2.1.jar
          - curator-recipes-5.2.1.jar
          - metrics-core-3.2.5.jar
          - netty-all-4.1.68.Final.jar
          - snappy-java-1.1.7.3.jar
          - xap-zookeeper.jar
          - zookeeper-3.6.3.jar
          - zookeeper-jute-3.6.3.jar
    upgrade:
  iidr:
    watchdog:
  kafka:
    jolokiaJar: jolokia-agent.jar
  kapacitor:
    alert:
    config:
      kapacitorconfigfile: kapacitor.conf.template
    templates:
  mq-connector:
    adabas:
      config:
        keystore: keystore.jks
        pipeline: data-pipeline.yml
      jars:
        jarFile: adabas-0.0.1-SNAPSHOT.jar
        kafkaConnector: kafka-connector-1.0.0-SNAPSHOT-jar-with-dependencies.jar
  mssql:
    config: null
    jars:
      mssqlJarFile: mssqlFeeder-1.0.0.jar
    scripts: null
  object:
    config:
      ddlparser:
        ts:
          bck:
            currentTs: null
            previousTs: null
        ddlBatchFileName: tableList.txt
        ddlCriteriaFileName: TieredCriteria.tab
    jars:
      management:
        objectmanagementjar: objectManagement.jar
      retention:
        retentionjar: retention-manager.jar
  security:
    jars:
      cef:
        cefjar: CEFLogger-1.0-SNAPSHOT.jar
      javapassword: JavaPasswordSDK.jar
      springldapcore: spring-ldap-core-2.3.3.RELEASE.jar
      springldapjar: spring-security-ldap-5.1.7.RELEASE.jar
      vaultsupportjar: VaultSupport-1.0-SNAPSHOT.jar
  telegraf:
    config:
      pivot:
        pivotconf: pivot.telegraf.conf
      space:
        spaceconf: space.telegraf.conf
    scripts:
      pivot:
      space:
    jars:
      readfromshobjar: readFromShob-1.0.0.jar
env_config:
  sqljdbc: SQLJDBCDriver.conf
  keytab: keytab
  ldapsourcefile: ldap-security-config.xml
utilities:
  check_manager_sync-sh: check_manager_sync.sh
  check_manager_sync-conf: check_manager_sync.conf
