servers :
  manager :
    host1 : 10.0.0.70
    host2 : 10.0.0.245
    host3 : 10.0.0.253
  space :
    host1 : 10.0.0.247
    host2 : 10.0.0.4
  dataIntegration :
    host1 : 10.0.0.1
    host2 : 10.0.0.2
    host3 : 10.0.0.3
    host4 : 10.0.0.4
  grafana :
    host1 : 10.0.0.137
  influxdb :
    host1 : 10.0.0.137
  nb_applicative :
    host1 : 10.0.0.149
    host2 : 10.0.0.153
    host3 : 10.0.0.114
  nb_management :
    host1 : 10.0.0.119