apiVersion: 1

providers:
  - name: 'Catalogue'
    orgId: 1
    folder: ''
    folderUid: ''
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    allowUiUpdates: false
    options:
      path:  /usr/share/grafana/conf/provisioning/dashboards/
      foldersFromFilesStructure: true
