{
 "title": "Main dashboard",
 "description": "v0.2",
 "tags": [
  "Master",
  "Main"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "   <a href=\"/d/tJWLBOR7qx/main-dashboard?orgId=1&refresh=5s&kiosk\">\n         <div>\n         <img alt=\"TAU Spaceboard\" src=\"/public/img/logo.png\"\n         width=150\">\n         <span style=\"font-size:150%; font-weight:bold ;color:darkblue; padding-left:10px; font-style:italic\"> SpaceBoard </span>\n         </div>\n      </a>\n   "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spaces list",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "space_active" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "space_data_data-types",
     "query": "SELECT mean(\"value\") FROM \"space_data_data-types\" WHERE (\"space_active\" = 'true') AND $timeFilter GROUP BY time($__interval), \"pu_name\", \"space_active\", \"space_name\" fill(null) LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "NB - Applicative",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "systemd_units",
     "query": "SELECT max(\"active_code\") FROM \"systemd_units\" WHERE (\"nb_role\" = 'application'  AND (\"name\" = 'nginx.service' OR \"name\" = 'consul-template.service' OR \"name\" = 'consul.service')) AND $timeFilter GROUP BY time($interval), \"host\" fill(none) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "active_code" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nb_role", "operator": "=", "value": "application" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "nginx.service" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "consul-template.service" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "consul.service" }
     ]
    }
   ]
  },
  {
   "title": "NB - Management",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "systemd_units",
     "query": "SELECT max(\"active_code\") FROM \"systemd_units\" WHERE (\"nb_role\" = 'management'  AND (\"name\" = 'nginx.service')) AND $timeFilter GROUP BY time($interval), \"host\" fill(none) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "active_code" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nb_role", "operator": "=", "value": "application" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "nginx.service" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "consul-template.service" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "consul.service" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_pu_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap_used-bytes",
     "query": "SELECT SUM(val) FROM (SELECT last(value) as val FROM \"jvm_memory_heap_used-bytes\" WHERE $timeFilter AND pu_name != '' GROUP BY \"pu_instance_id\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "!=", "value": "data-feeder-spaceB" }
     ]
    }
   ]
  },
  {
   "title": "Data Validation Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"result\") FROM \"dvState\" WHERE $timeFilter GROUP BY \"obj_type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Freshness Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"freshness\") FROM \"shobStatus\" WHERE $timeFilter GROUP BY \"table_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "process_cpu_used-percent",
     "query": "SELECT last(\"value\") FROM \"process_cpu_used-percent\" WHERE pu_name != '' and $timeFilter GROUP BY time($__interval), \"pu_name\" fill(null) LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_pu_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pu_ServiceRoute_service-latency",
     "query": "SELECT last(\"value\") FROM \"pu_ServiceRoute_service-latency\" WHERE $timeFilter GROUP BY time($__interval), \"pu_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_pu_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap_used-bytes",
     "query": "SELECT SUM(val) FROM (SELECT last(value) as val FROM \"jvm_memory_heap_used-bytes\" WHERE  pu_name != ''  AND $timeFilter GROUP BY  pu_instance_id) where val != 0 GROUP BY  pu_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "!=", "value": "data-feeder-spaceB" }
     ]
    }
   ]
  },
  {
   "title": "Entries per object type",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_space_name : $tag_data_type_short_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "data_type_short_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_data_data-types",
     "query": "SELECT SUM(val) FROM (SELECT last(value) as val FROM \"space_data_data-types\"  WHERE (\"space_active\" = 'true' AND \"data_type_name\" != 'java.lang.Object' AND $timeFilter )  GROUP BY data_type_name, pu_instance_id) where val != 0 GROUP BY data_type_short_name, space_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "data_type_name", "operator": "!=", "value": "java.lang.Object" },
      { "condition": "AND", "key": "data_type_short_name", "operator": "!=", "value": "Value" }
     ]
    }
   ]
  },
  {
   "title": "Grid CPU %",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "os_cpu_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Memory %",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "os_memory_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Northbound CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"value\") FROM \"os_cpu_used-percent\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nb_role", "operator": "=", "value": "application" },
      { "condition": "OR", "key": "nb_role", "operator": "=", "value": "management" }
     ]
    }
   ]
  },
  {
   "title": "Northbound Memory %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"nb_role\" = 'application') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nb_role", "operator": "=", "value": "application" },
      { "condition": "OR", "key": "nb_role", "operator": "=", "value": "management" }
     ]
    }
   ]
  }
 ]
}